[package]
name = "buildspace-timer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
system_status_bar_macos = "0.1.3"
tokio = { version = "1.38.0", features = ["full"] }
webbrowser = "1.0.1"
